#!/bin/bash

# Iniciar la máquina virtual y conectarse a ella usando Guest Additions (sin pedir contraseñas ni comandos manuales).

# Detectar automáticamente la IP de la VM (red en modo puente).

# Particionar, formatear y montar el disco nuevo automáticamente.

# Configurar el montaje persistente (por ejemplo, en /etc/fstab).

# Evitar dañar datos si se ejecuta otra vez sobre una VM ya configurada (no formatear de nuevo).

# Probar todo con al menos 2 máquinas virtuales.

# Medir cuánto tarda el proceso varias veces y analizar diferencias.

# Hacer un diagrama del escenario (host, VirtualBox, VMs, IPs, disco, flujo).

# Documentar la solución, pruebas, problemas, referencias y uso de IA.

# Entregar máximo el 05 de octubre de 2026 y sustentar el 06 de octubre.
